version: '2.1'
services:
  iotedge:
    build:
      context: ./iotedge
    restart: 'no'
    privileged: true
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.balena-socket: '1'